/**
 * Local development seed data: an admin account, a few test users (some
 * pending OTP verification, one already active), demo IoT devices with
 * device-agent API keys the simulator can authenticate with, and enough
 * historical telemetry / connection-log / order data for the dashboards to
 * have something to show immediately.
 *
 * Run with: npx prisma db seed  (or it runs automatically after
 * `prisma migrate dev`).
 *
 * Safe to re-run: users and devices are upserted by a fixed id, and the
 * historical rows this script owns (telemetry, connection logs, OTA jobs,
 * the two seeded orders) are cleared and regenerated each time, so running
 * it twice just refreshes the demo data instead of erroring on a unique
 * constraint.
 */
import crypto from "node:crypto";
import { PrismaClient, type Prisma } from "@prisma/client";
import { hashPassword, sha256Hex } from "../src/utils/hash";
import { storeFirmwareFile } from "../src/services/firmware.service";

const prisma = new PrismaClient();

const ADMIN_PASSWORD = "AdminSecure2026!";
const TEST_USER_PASSWORD = "TestUser123!";

const ADMIN_ID = "11111111-1111-4111-8111-111111111111";
const ALICE_ID = "22222222-2222-4222-8222-222222222222";
const BOB_ID = "33333333-3333-4333-8333-333333333333";
const CAROL_ID = "44444444-4444-4444-8444-444444444444";

const DEVICE_1_ID = "a1111111-1111-4111-8111-111111111111"; // Living Room Sensor (Carol) — has a pending OTA job
const DEVICE_2_ID = "a2222222-2222-4222-8222-222222222222"; // Garage Door Controller (Carol)
const DEVICE_3_ID = "a3333333-3333-4333-8333-333333333333"; // Greenhouse Monitor (Alice)
const DEVICE_4_ID = "a4444444-4444-4444-8444-444444444444"; // Warehouse Beacon (Bob)
const DEVICE_5_ID = "a5555555-5555-4555-8555-555555555555"; // Unassigned demo unit

const ORDER_1_ID = "b1111111-1111-4111-8111-111111111111";
const ORDER_2_ID = "b2222222-2222-4222-8222-222222222222";

const PRODUCT_ENV_ID = "c1111111-1111-4111-8111-111111111111";
const PRODUCT_RELAY_ID = "c2222222-2222-4222-8222-222222222222";
const PRODUCT_GPS_ID = "c3333333-3333-4333-8333-333333333333";
const PRODUCT_DRAFT_ID = "c4444444-4444-4444-8444-444444444444";

type SeedDeviceStatus = "ONLINE" | "OFFLINE" | "DISABLED";

interface DeviceSeed {
  id: string;
  serialNumber: string;
  name: string;
  model: string;
  hardwareRevision: string;
  ownerId: string | null;
  status: SeedDeviceStatus;
  firmwareVersion: string;
  // Demo-only device credential, intentionally simple/public. A real
  // provisioned device gets a random key generated by
  // POST /api/admin/devices (see server/src/routes/admin/devices.routes.ts),
  // never a hardcoded one like this.
  apiKey: string;
}

const DEVICE_SEEDS: DeviceSeed[] = [
  {
    id: DEVICE_1_ID,
    serialNumber: "SIM-ENV-001",
    name: "Living Room Sensor",
    model: "ESP32-ENV-V1",
    hardwareRevision: "RevB",
    ownerId: CAROL_ID,
    status: "ONLINE",
    firmwareVersion: "1.0.0",
    apiKey: "demo-device-key-env-001",
  },
  {
    id: DEVICE_2_ID,
    serialNumber: "SIM-RELAY-002",
    name: "Garage Door Controller",
    model: "ESP32-RELAY-V2",
    hardwareRevision: "RevA",
    ownerId: CAROL_ID,
    status: "OFFLINE",
    firmwareVersion: "1.0.0",
    apiKey: "demo-device-key-relay-002",
  },
  {
    id: DEVICE_3_ID,
    serialNumber: "SIM-ENV-003",
    name: "Greenhouse Monitor",
    model: "ESP32-ENV-V1",
    hardwareRevision: "RevB",
    ownerId: ALICE_ID,
    status: "ONLINE",
    firmwareVersion: "0.9.5",
    apiKey: "demo-device-key-env-003",
  },
  {
    id: DEVICE_4_ID,
    serialNumber: "SIM-GPS-004",
    name: "Warehouse Beacon",
    model: "ESP32-GPS-V1",
    hardwareRevision: "RevA",
    ownerId: BOB_ID,
    status: "OFFLINE",
    firmwareVersion: "1.0.0",
    apiKey: "demo-device-key-gps-004",
  },
  {
    id: DEVICE_5_ID,
    serialNumber: "SIM-ENV-005",
    name: "Unassigned Demo Unit",
    model: "ESP32-ENV-V1",
    hardwareRevision: "RevB",
    ownerId: null,
    status: "DISABLED",
    firmwareVersion: "1.0.0",
    apiKey: "demo-device-key-env-005",
  },
];

async function seedUsers() {
  const adminPasswordHash = await hashPassword(ADMIN_PASSWORD);
  await prisma.user.upsert({
    where: { id: ADMIN_ID },
    update: {},
    create: {
      id: ADMIN_ID,
      email: "admin@iot-platform.local",
      passwordHash: adminPasswordHash,
      fullName: "Platform Admin",
      role: "ADMIN",
      status: "ACTIVE",
    },
  });

  const testPasswordHash = await hashPassword(TEST_USER_PASSWORD);

  await prisma.user.upsert({
    where: { id: ALICE_ID },
    update: {},
    create: {
      id: ALICE_ID,
      email: "alice@example.com",
      passwordHash: testPasswordHash,
      fullName: "Alice Example",
      role: "USER",
      status: "PENDING",
    },
  });

  await prisma.user.upsert({
    where: { id: BOB_ID },
    update: {},
    create: {
      id: BOB_ID,
      email: "bob@example.com",
      passwordHash: testPasswordHash,
      fullName: "Bob Example",
      role: "USER",
      status: "PENDING",
    },
  });

  await prisma.user.upsert({
    where: { id: CAROL_ID },
    update: {},
    create: {
      id: CAROL_ID,
      email: "carol@example.com",
      passwordHash: testPasswordHash,
      fullName: "Carol Example",
      role: "USER",
      status: "ACTIVE",
    },
  });

  // Predefined OTP codes so POST /api/auth/verify-otp can be exercised
  // end-to-end without a real inbox. A far-future expiry keeps them usable
  // for the life of a local dev session — the real issueOtp() flow uses a
  // strict 10-minute TTL; this is a test fixture, not the production path.
  const farFuture = new Date(Date.now() + 365 * 24 * 60 * 60 * 1000);
  await prisma.otpCode.deleteMany({
    where: { userId: { in: [ALICE_ID, BOB_ID] }, purpose: "REGISTRATION" },
  });
  await prisma.otpCode.createMany({
    data: [
      { userId: ALICE_ID, purpose: "REGISTRATION", codeHash: sha256Hex("111111"), expiresAt: farFuture },
      { userId: BOB_ID, purpose: "REGISTRATION", codeHash: sha256Hex("222222"), expiresAt: farFuture },
    ],
  });
}

async function seedDevices() {
  for (const d of DEVICE_SEEDS) {
    const shared = {
      serialNumber: d.serialNumber,
      name: d.name,
      model: d.model,
      hardwareRevision: d.hardwareRevision,
      ownerId: d.ownerId,
      status: d.status,
      firmwareVersion: d.firmwareVersion,
      apiKeyHash: sha256Hex(d.apiKey),
      lastSeenAt: d.status === "ONLINE" ? new Date() : null,
    };

    await prisma.device.upsert({
      where: { id: d.id },
      update: shared,
      create: { id: d.id, createdByAdminId: ADMIN_ID, ...shared },
    });
  }
}

async function resetHistoricalData() {
  const deviceIds = DEVICE_SEEDS.map((d) => d.id);
  await prisma.deviceTelemetry.deleteMany({ where: { deviceId: { in: deviceIds } } });
  await prisma.deviceConnectionLog.deleteMany({ where: { deviceId: { in: deviceIds } } });
  await prisma.firmwareUpdateJob.deleteMany({ where: { deviceId: { in: deviceIds } } });
  await prisma.orderStatusHistory.deleteMany({ where: { orderId: { in: [ORDER_1_ID, ORDER_2_ID] } } });
  await prisma.orderItem.deleteMany({ where: { orderId: { in: [ORDER_1_ID, ORDER_2_ID] } } });
  await prisma.order.deleteMany({ where: { id: { in: [ORDER_1_ID, ORDER_2_ID] } } });
}

function hoursAgo(h: number): Date {
  return new Date(Date.now() - h * 60 * 60 * 1000);
}

async function seedTelemetryAndLogs() {
  const telemetryRows: { deviceId: string; metric: string; value: number; unit: string; recordedAt: Date }[] = [];

  for (const d of DEVICE_SEEDS) {
    for (let i = 12; i >= 0; i--) {
      const recordedAt = hoursAgo(i);
      telemetryRows.push(
        {
          deviceId: d.id,
          metric: "temperature",
          value: Number((20 + Math.sin(i / 2) * 3 + Math.random()).toFixed(1)),
          unit: "°C",
          recordedAt,
        },
        {
          deviceId: d.id,
          metric: "humidity",
          value: Number((45 + Math.cos(i / 3) * 8 + Math.random() * 2).toFixed(1)),
          unit: "%",
          recordedAt,
        },
        {
          deviceId: d.id,
          metric: "batteryLevel",
          value: Number(Math.max(15, 100 - i * 1.5).toFixed(0)),
          unit: "%",
          recordedAt,
        },
      );
    }
  }
  await prisma.deviceTelemetry.createMany({ data: telemetryRows });

  const connectionLogRows: {
    deviceId: string;
    event: "CONNECTED" | "DISCONNECTED" | "FORCED_STATE_CHANGE";
    ipAddress: string;
    detail: string | null;
    occurredAt: Date;
  }[] = [];

  DEVICE_SEEDS.forEach((d, index) => {
    const ip = `10.0.0.${10 + index}`;
    for (let i = 8; i >= 1; i--) {
      connectionLogRows.push({
        deviceId: d.id,
        event: i % 2 === 0 ? "DISCONNECTED" : "CONNECTED",
        ipAddress: ip,
        detail: null,
        occurredAt: hoursAgo(i * 2),
      });
    }
    // End on an event consistent with the device's current seeded status.
    connectionLogRows.push({
      deviceId: d.id,
      event: d.status === "ONLINE" ? "CONNECTED" : "DISCONNECTED",
      ipAddress: ip,
      detail: null,
      occurredAt: hoursAgo(0.5),
    });
  });

  connectionLogRows.push({
    deviceId: DEVICE_5_ID,
    event: "FORCED_STATE_CHANGE",
    ipAddress: "10.0.0.14",
    detail: "Admin forced state ONLINE -> DISABLED. Reason: Awaiting customer assignment.",
    occurredAt: hoursAgo(1),
  });

  await prisma.deviceConnectionLog.createMany({ data: connectionLogRows });
}

async function seedOrders() {
  await prisma.order.create({
    data: {
      id: ORDER_1_ID,
      userId: CAROL_ID,
      status: "DELIVERED",
      totalCents: 7999,
      createdAt: hoursAgo(96),
      items: {
        create: [{ productName: "IoT Starter Kit — Environment Sensor Bundle", quantity: 1, unitPriceCents: 7999 }],
      },
      statusHistory: {
        create: [
          { status: "AWAITING_CONFIRMATION", changedById: null, changedAt: hoursAgo(96), note: "Order placed." },
          { status: "CONFIRMED", changedById: ADMIN_ID, changedAt: hoursAgo(72), note: "Payment confirmed." },
          { status: "IN_TRANSIT", changedById: ADMIN_ID, changedAt: hoursAgo(48), note: "Shipped via courier." },
          { status: "DELIVERED", changedById: ADMIN_ID, changedAt: hoursAgo(24), note: "Delivered to customer." },
        ],
      },
    },
  });

  await prisma.order.create({
    data: {
      id: ORDER_2_ID,
      userId: CAROL_ID,
      status: "IN_TRANSIT",
      totalCents: 6998,
      createdAt: hoursAgo(48),
      items: { create: [{ productName: "Smart Relay Controller", quantity: 2, unitPriceCents: 3499 }] },
      statusHistory: {
        create: [
          { status: "AWAITING_CONFIRMATION", changedById: null, changedAt: hoursAgo(48), note: "Order placed." },
          { status: "CONFIRMED", changedById: ADMIN_ID, changedAt: hoursAgo(24), note: "Payment confirmed." },
          { status: "IN_TRANSIT", changedById: ADMIN_ID, changedAt: hoursAgo(12), note: "Shipped via courier." },
        ],
      },
    },
  });
}

async function seedFirmwareAndOtaJob() {
  let firmware = await prisma.firmware.findUnique({
    where: { model_version: { model: "ESP32-ENV-V1", version: "1.1.0" } },
  });

  if (!firmware) {
    // Reuses the same validated storage path a real admin upload goes
    // through (server/src/services/firmware.service.ts), so this fixture
    // can't drift from what the real upload/OTA flow actually accepts.
    const mockBinary = crypto.randomBytes(8192);
    const stored = await storeFirmwareFile("seed-mock-firmware-v1.1.0.bin", mockBinary);
    firmware = await prisma.firmware.create({
      data: {
        version: "1.1.0",
        model: "ESP32-ENV-V1",
        filePath: stored.filePath,
        checksumSha256: stored.checksumSha256,
        fileSizeBytes: stored.fileSizeBytes,
        uploadedById: ADMIN_ID,
      },
    });
  }

  // Ready for the simulator to discover immediately: run it pointed at
  // DEVICE_1 (Living Room Sensor, the default config) and it will find,
  // download, and "flash" this job on its first OTA poll.
  await prisma.firmwareUpdateJob.create({
    data: { firmwareId: firmware.id, deviceId: DEVICE_1_ID, status: "SCHEDULED", createdById: ADMIN_ID },
  });
}

async function seedProducts() {
  const products: {
    id: string;
    title: string;
    description: string;
    priceCents: number;
    stockQuantity: number;
    specs: { label: string; value: string }[];
    status: "DRAFT" | "PUBLISHED";
  }[] = [
    {
      id: PRODUCT_ENV_ID,
      title: "Environment Sensor",
      description: "Temperature, humidity, and air quality in one compact unit.",
      priceCents: 7999,
      stockQuantity: 42,
      specs: [
        { label: "MCU", value: "ESP32-WROOM-32" },
        { label: "Sensors", value: "Temp / Humidity / VOC" },
        { label: "Connectivity", value: "Wi-Fi 802.11 b/g/n" },
        { label: "Battery life", value: "~6 months" },
      ],
      status: "PUBLISHED",
    },
    {
      id: PRODUCT_RELAY_ID,
      title: "Smart Relay Controller",
      description: "Remotely switch garage doors, valves, and mains-powered devices.",
      priceCents: 3499,
      stockQuantity: 3,
      specs: [
        { label: "MCU", value: "ESP32-S3" },
        { label: "Relay rating", value: "10A @ 250VAC" },
        { label: "Connectivity", value: "Wi-Fi + Bluetooth LE" },
        { label: "Response time", value: "< 200ms" },
      ],
      status: "PUBLISHED",
    },
    {
      id: PRODUCT_GPS_ID,
      title: "Warehouse Beacon",
      description: "Asset-level GPS tracking with geofencing alerts.",
      priceCents: 12999,
      stockQuantity: 17,
      specs: [
        { label: "MCU", value: "ESP32-WROVER" },
        { label: "GPS", value: "u-blox NEO-M9N" },
        { label: "Connectivity", value: "LTE-M / NB-IoT" },
        { label: "Battery life", value: "~14 days active" },
      ],
      status: "PUBLISHED",
    },
    {
      id: PRODUCT_DRAFT_ID,
      title: "Cold Chain Monitor (coming soon)",
      description: "Continuous temperature logging for refrigerated shipments.",
      priceCents: 15999,
      stockQuantity: 0,
      specs: [
        { label: "MCU", value: "ESP32-S3" },
        { label: "Sensors", value: "Dual thermocouple" },
        { label: "Connectivity", value: "LTE-M" },
      ],
      status: "DRAFT",
    },
  ];

  for (const p of products) {
    const shared = {
      title: p.title,
      description: p.description,
      priceCents: p.priceCents,
      stockQuantity: p.stockQuantity,
      specs: p.specs as Prisma.InputJsonValue,
      status: p.status,
    };
    await prisma.product.upsert({
      where: { id: p.id },
      update: shared,
      create: { id: p.id, createdById: ADMIN_ID, ...shared },
    });
  }
}

async function main() {
  await seedUsers();
  await seedDevices();
  await resetHistoricalData();
  await seedTelemetryAndLogs();
  await seedOrders();
  await seedFirmwareAndOtaJob();
  await seedProducts();

  console.log("\nSeed complete.\n");
  console.log("Admin login:                        admin@iot-platform.local / AdminSecure2026!");
  console.log("Test user, active:                  carol@example.com / TestUser123!");
  console.log("Test user, pending (OTP 111111):    alice@example.com / TestUser123!");
  console.log("Test user, pending (OTP 222222):    bob@example.com / TestUser123!");
  console.log("\nSeeded device credentials (defaults already match simulator/config.ts):");
  for (const d of DEVICE_SEEDS) {
    console.log(`  ${d.name.padEnd(24)} id=${d.id}  key=${d.apiKey}`);
  }
  console.log("\nA SCHEDULED firmware update job is waiting for the Living Room Sensor device.");
  console.log("3 published storefront products + 1 draft (Smart Relay Controller is low-stock at 3 units).");
}

main()
  .catch((err) => {
    console.error(err);
    process.exitCode = 1;
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
